#数据源的配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/a?serverTimezone = GMT
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  #应用的名称
  application:
    name: teacherconsume
  main:
    allow-bean-definition-overriding: true

#mybatis扫描配置文件
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.eurekateacher.po
#eureka的配置
server:
  port: 3100
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: true
    serviceUrl:
      defaultZone: http://root:root@localhost:8260/eureka/
#feign开启容错机制
feign:
  hystrix:
    enabled: true
#断路器设置


